development:
  adapter: postgresql
  encoding: unicode
  database: devise_app_local
  pool: 5
  username: postgres
  password: Resa312!
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: devise_app_test # TAKE CARE
  pool: 5
  username: postgres
  password: Resa312!
  host: localhost

# production:
#   adapter: postgresql
#   database: db/production.sqlite3
#   pool: 5
#   timeout: 5000
